alter table public.sesiones add column if not exists grado text;
alter table public.sesiones add column if not exists tipo text;
create index if not exists sesiones_tipo_idx on public.sesiones(tipo);
create index if not exists sesiones_inicio_idx on public.sesiones(inicio);
alter table public.sesiones enable row level security;
drop policy if exists "sesiones_public_select_estudiantes" on public.sesiones;
drop policy if exists "sesiones_public_insert_estudiantes" on public.sesiones;
drop policy if exists "sesiones_public_update_estudiantes" on public.sesiones;
create policy "sesiones_public_select_estudiantes" on public.sesiones for select to anon, authenticated using (tipo='estudiante');
create policy "sesiones_public_insert_estudiantes" on public.sesiones for insert to anon, authenticated with check (tipo='estudiante');
create policy "sesiones_public_update_estudiantes" on public.sesiones for update to anon, authenticated using (tipo='estudiante') with check (tipo='estudiante');
